### ISSUE TITLE
:datum not rendering

### ISSUE THREAD

**Issue by bombaywalla** [metasoarous/oz#121]
I was trying to use :datum as per [this vega-lite example](https://vega.github.io/vega-lite/docs/datum.html)
for a horizontal rule. That does not seem to work in the latest Oz (1.6.0-alpha6).

I tried using the following small example

```
  (require '[oz.core :as oz] :reload)
  (oz/start-server!)
  (def x {:layer
          [{:data {:values [{"x" 1 "y" 10} {"x" 2 "y" 20} {"x" 3 "y" 30}]}
            :mark "line"
            :encoding {:x {:field "x", :type "quantitative"}
                       :y {:field "y", :type "quantitative"}}}
           {:data {:values [{}]}
            :mark {:type "rule" :size 4 :color "red"}
            :encoding {:y {:datum 5}}}
           ]
          })
  (oz/view! x)
```

When I run the above, I get the following in the Chrome console.

> oz.js:14 WARN Dropping {"datum":5} from channel "y" since it does not contain data field or value.
> 
> TypeError: vegaTooltip.vegaLite is not a function
>     at oz.js:1205

The first layer displays fine.  The second layer (the "rule" layer) does not.

I thought that the problem might be because I did not have the latest vega-lite.  So, I tried the script in the bin directory and instructions to update my local version of vega-lite.  The latest vega-lite (4.13.1-0), vega-tooltips and vega-extras compiled fine without warnings.  However vega had about 125 warnings.  I was not able to quite debug those.  But assuming that they were just warnings, and not errors, I proceeded to use the latest versions locally.  That still did not help.  I still get the same messages on the Chrome JS console.

**Comment by bombaywalla** [comment]
For the record... I also confirmed that translating the above Clojure to JSON and then using the vega-lite editor worked as expected.

**Comment by metasoarous** [comment]
Hey @bombaywalla. Thanks for reporting.

Please give `1.6.0-alpha7-SNAPSHOT` a try and let me know if that works for you.

Thanks!

**Comment by bombaywalla** [comment]
Just tried it.  Works now!!
Thanks so much.
Should I close this issue? Or will you?

**Comment by metasoarous** [comment]
Wonderful! Thank you!

I'm happy to close the issue, but feel free to close yourself in the future if you're satisfied the issue has been resolved if you like.

Also, please note that I just released `1.6.0-alpha8` with a couple of fixes.

Thanks again!
